server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/v1

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDB_HOST}:${RDB_PORT}/${RDB_SCHEMA}?createDatabaseIfNotExist=true
    username: ${RDB_USER}
    password: ${RDB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}/${MONGODB_SCHEMA}?retryWrites=true&w=majority&appName=${MONGODB_SCHEMA}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 10
      password: ${REDIS_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret_key: ${JWT_SECRET}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
  cloud:
    id: ${NAVER_CLOUD_ID}
    secret: ${NAVER_CLOUD_SECRET}

pingping:
  share:
    base-url: ${BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info